services:
  derper:
    image: yujibuzailai/derper
    container_name: derper
    restart: always
    environment:
      - DERP_STUN=true # 是否开启stun，默认开启
      - DERP_VERIFY_CLIENTS=true # 开启防止白嫖，本机需要先加入tailscale节点
    ports:
      - '3478:3478/udp'
      - '50443:443'
