name: Docker Image CI

on: #触发条件
#  push: # 1.推送
#    branches: [ "main" ]
    
#  pull_request: # 2.拉取
#    branches: [ "main" ]
    
  watch: # 3.手动点击收藏
    types: [started]
jobs:

  build_image:

    runs-on: ubuntu-latest #申请一个ubuntu的虚拟机

    steps:
    - name: 1.Checkout Code # 第一步，获取代码
      uses: actions/checkout@v4 # 官方的action，获取代码

    - name: 2.Build image # 第二步，构建docker镜像
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCK_IMAGE_NAME }}

    - name: 3.Log in to Docker Hub # 第三步，登录docker hub
      uses: docker/login-action@v3  # 三方的action操作， 执行docker login
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}  # 配置dockerhub的认证，在Github项目主页 【Settings】 -> 【Secrets】 添加对应变量
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: 4.Push image # 第四步，推送镜像到docker hub 
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCK_IMAGE_NAME }}
